### PR TITLE
Add Visual Studio 2017 support using changes from Chromium project

### PR DESCRIPTION
**Pull request by torycl**
I have merged electron/gyp with changes from https://chromium.googlesource.com/external/gyp so Electron can be built with Visual Studio 2017 on Windows.
One more little change has been needed so paths in generated ninja files remain functional.

I have tested this with electron on Windows 10 with Visual Studio 2017 and 2015 and with electron "upgrade-to-chromium-63" branch.

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
cc @zcbenz 

We probably shouldn't have our changes in the master branch, and should use "release" branches instead.

So I would suggest to create a separate branch with the new stuff from the upstream,
cherry-pick 549e55a22765ccf99e46b419b2dff6338bcac64a and make all other changes there.

**Comment by zcbenz** [comment]
@alexeykuzmin Sounds good to me, I'll created a new branch with upstream changes.

**Comment by zcbenz** [comment]
The gyp repo does not have any release branch, nor tags, I'm going to name our branches with `gyp-YYYYMMDD`.

**Comment by zcbenz** [comment]
I have pushed the changes to the `gyp-20171012` branch.

**Pull request closed without merging**
